// Code generated by qtc from "converter.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/generators/converter.qtpl:1
package generators

//line pkg/generators/converter.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/generators/converter.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/generators/converter.qtpl:1
func streamdefaultValueExprTemplate(qw422016 *qt422016.Writer, ctx tplContext) {
//line pkg/generators/converter.qtpl:1
	qw422016.N().S(`
    `)
//line pkg/generators/converter.qtpl:2
	qw422016.E().S(ctx.Out.Name().Obj().Name())
//line pkg/generators/converter.qtpl:2
	qw422016.N().S(`{}
`)
//line pkg/generators/converter.qtpl:3
}

//line pkg/generators/converter.qtpl:3
func writedefaultValueExprTemplate(qq422016 qtio422016.Writer, ctx tplContext) {
//line pkg/generators/converter.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/generators/converter.qtpl:3
	streamdefaultValueExprTemplate(qw422016, ctx)
//line pkg/generators/converter.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line pkg/generators/converter.qtpl:3
}

//line pkg/generators/converter.qtpl:3
func defaultValueExprTemplate(ctx tplContext) string {
//line pkg/generators/converter.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/generators/converter.qtpl:3
	writedefaultValueExprTemplate(qb422016, ctx)
//line pkg/generators/converter.qtpl:3
	qs422016 := string(qb422016.B)
//line pkg/generators/converter.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/generators/converter.qtpl:3
	return qs422016
//line pkg/generators/converter.qtpl:3
}

//line pkg/generators/converter.qtpl:5
func streamstructResultTemplate(qw422016 *qt422016.Writer, ctx tplContext) {
//line pkg/generators/converter.qtpl:5
	qw422016.N().S(`
`)
//line pkg/generators/converter.qtpl:6
	if ctx.Out.IsPtr() {
//line pkg/generators/converter.qtpl:6
		qw422016.N().S(`&`)
//line pkg/generators/converter.qtpl:6
	}
//line pkg/generators/converter.qtpl:6
	qw422016.E().S(ctx.Out.Name().Obj().Name())
//line pkg/generators/converter.qtpl:6
	qw422016.N().S(`{
`)
//line pkg/generators/converter.qtpl:7
	for _, field := range ctx.Out.Fields() {
//line pkg/generators/converter.qtpl:8
		inField := ctx.In.FieldByName(field.Name())

//line pkg/generators/converter.qtpl:9
		if inField == nil {
//line pkg/generators/converter.qtpl:9
			qw422016.N().S(`    `)
//line pkg/generators/converter.qtpl:10
			qw422016.E().S(field.Name())
//line pkg/generators/converter.qtpl:10
			qw422016.N().S(`: `)
//line pkg/generators/converter.qtpl:10
			qw422016.E().S(emptyField(field))
//line pkg/generators/converter.qtpl:10
			qw422016.N().S(`, // todo
`)
//line pkg/generators/converter.qtpl:11
			continue
//line pkg/generators/converter.qtpl:12
		}
//line pkg/generators/converter.qtpl:12
		qw422016.N().S(`    `)
//line pkg/generators/converter.qtpl:13
		qw422016.E().S(field.Name())
//line pkg/generators/converter.qtpl:13
		qw422016.N().S(`: `)
//line pkg/generators/converter.qtpl:13
		qw422016.N().S(convertField(ctx.In.VarName(), inField, field))
//line pkg/generators/converter.qtpl:13
		qw422016.N().S(`,
`)
//line pkg/generators/converter.qtpl:14
	}
//line pkg/generators/converter.qtpl:14
	qw422016.N().S(`}
`)
//line pkg/generators/converter.qtpl:15
}

//line pkg/generators/converter.qtpl:15
func writestructResultTemplate(qq422016 qtio422016.Writer, ctx tplContext) {
//line pkg/generators/converter.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/generators/converter.qtpl:15
	streamstructResultTemplate(qw422016, ctx)
//line pkg/generators/converter.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line pkg/generators/converter.qtpl:15
}

//line pkg/generators/converter.qtpl:15
func structResultTemplate(ctx tplContext) string {
//line pkg/generators/converter.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/generators/converter.qtpl:15
	writestructResultTemplate(qb422016, ctx)
//line pkg/generators/converter.qtpl:15
	qs422016 := string(qb422016.B)
//line pkg/generators/converter.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/generators/converter.qtpl:15
	return qs422016
//line pkg/generators/converter.qtpl:15
}
